name: git diff
description: Generates file change log between 2 git refs
branding:
  icon: git-branch
  color: gray-dark
inputs:
  head-ref:
    description: git ref to use as head
    required: false
    default: HEAD
  base-ref:
    description: git ref to use as base
    required: false
    default: HEAD~1
  default-branch:
    description: git branch to use as reference for `HEAD`
    required: false
    default: ${{ github.ref_name }}
  status:
    description: Change status of the files to filter by. See https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---diff-filterACDMRTUXB82308203
    required: false
    default: d
  filename-pattern:
    description: Filename pattern to filter by
    required: false
    default: '**/*'
  token:
    description: GitHub token to use for authentication
    required: false
    default: ${{ github.token }}
outputs:
  filenames:
    description: A JSON array of filenames that changed
runs:
  using: node20
  main: dist/index.js
