name: QA

on:
  push:
  pull_request:
    types:
    - opened
    - synchronize

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Generate Changed Filenames
      id: git-diff
      uses: swaglive/action-git-diff@main
      env:
        OBJ: ${{ toJSON(github.event) }}
      with:
        head-ref: ${{ github.event.pull_request.head.sha || github.event.after || 'HEAD' }}
        base-ref: ${{ github.event.pull_request.base.sha || github.event.before || 'HEAD~1' }}
        filename-pattern: |-
          **/*.js